# Generated by Django 4.1.3 on 2022-11-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_rating',
            new_name='rating',
        ),
    ]
