# Generated by Django 4.1.3 on 2022-11-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_categorysubscriber_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='CategorySubscriber',
        ),
    ]
